spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 82642993728-0oojjad814iedrvar5fs6vro8av8ljkk.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email

          naver:
            client-name: Naver
            client-id: B1ROklT2yyReArghOlll
            client-secret: 8MoTcOG9cG
            #  (== http://localhost:8080/login/oauth2/code/naver)
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization_grant_type: authorization_code
            scope:
              - name
              - email
              - profile_image

          kakao:
            client-name: kakao
            client-id: eba8754dd790ccdbd7dd42db15165dcf
            client-secret: GJllf3hWGKXRocuEp1EiPP2BHe4P3nRo
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            scope:
              - profile_nickname
              - profile_image
              - account_email

        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
